runner:
  govet:
    cmd: go vet $(go list ./... | grep -v /vendor/)
    format: govet
  staticcheck:
    cmd: staticcheck $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  golangci:
    cmd: golangci-lint run --out-format=line-number --timeout=10m ./...
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
    level: warning