name: lint

on:
  pull_request:

jobs:
  reviewdog:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/golangci-lint
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golangcilint-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golangcilint-
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-review -runners=golint,govet -level=warning -fail-on-error --timeout=10m